# Generated by Django 5.0.4 on 2024-05-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlavourQuest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='api_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
